# -*- coding: utf-8 -*-
"""Seaborn_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OGmFO-PAVGsWGsPTMnRdQt7UUrfoeDAg
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

sns.set_style('whitegrid')

titanic = sns.load_dataset('titanic')

titanic.head()

titanic = titanic.dropna(subset=['age', 'fare'])

g = sns.jointplot(x="fare", y="age", data=titanic, kind="scatter", marginal_kws=dict(bins=30, fill=True))

plt.hist(titanic['fare'], bins=30, color='red', alpha=0.5)
plt.xlabel('fare')
plt.ylabel('count')
plt.show()

sns.boxplot(x="class", y="age", data=titanic)

plt.show()

sns.stripplot(x="class", y="age", data=titanic, palette=["red", "lightgreen", "skyblue"])
plt.show()

sns.countplot(x="sex", data=titanic, palette=["lightgreen", "pink"])

corr = titanic.corr(numeric_only=True)

sns.heatmap(corr, annot=False, cmap="coolwarm", center=0)

plt.title("titanic.corr()")
plt.show()

g = sns.FacetGrid(titanic, col="sex")
g.map(plt.hist, "age", bins=15, color="steelblue")

plt.show()

